sudo: false
language: node_js
node_js:
  - lts/*
cache:
  yarn: true
  directories:
    - node_modules
script:
  - jest --coverage && cat ./coverage/lcov.info | coveralls
after_success:
  - yarn semantic-release
branches:
  only: master
